In [2]:
import numpy as np

In [19]:
xdsc = np.arange(0,10)[::-1]
print(xasc)


[9 8 7 6 5 4 3 2 1 0]


In [23]:
xx = np.diag(xdsc)
print(xx)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [24]:
xx.sum()

45

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [5]:
a  = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
print(a)

[[4 2 1]
 [1 3 0]
 [0 5 4]]


In [6]:
from numpy import linalg

In [7]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [8]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [34]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [36]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [37]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [47]:
list_ = []
for user in users_stats:
    list_.append(cosine(user, next_user_stats))

print(f'Самый похожий пользователь под номером {list_.index(max(list_)) + 1}')


Самый похожий пользователь под номером 8
